# help from https://medium.com/@evanca/set-up-your-portfolio-website-in-less-than-10-minutes-with-github-pages-d0efa8ff56fd
title: Laura W. Dozal # your name (or website title) here
logo: "/images/cool.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computational Social Scientist Specializing in information behavior and visual analysis.
  <br><br>
  PhD Candidate at the University of Arizona's School of Information. Methods Expert in Network Analysis, Machine Learning, and Data Mining
  <br><br>
  <a href="https://www.linkedin.com/in/laurawerthmann/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
