# help from https://medium.com/@evanca/set-up-your-portfolio-website-in-less-than-10-minutes-with-github-pages-d0efa8ff56fd
title: Laura W. Dozal # your name (or website title) here
logo: "/images/cool2.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 PhD Candidate at the University of Arizona’s College of Information (iSchool). Computational Social Scientist with 6+ years of specialization in information behavior and visual analysis through Computer Vision, Natural Language Processings, Graph Science and knowledge discovery.
  <br><br>
  <a href="https://github.com/lwdozal/lwdozal.github.io/blob/master/pdf/LauraW_Dozal_CV 2024.pdf">Download My Resume/CV</a> <br>
  <a href="https://www.linkedin.com/in/laurawerthmann/">View My LinkedIn Profile</a>  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
