# help from https://medium.com/@evanca/set-up-your-portfolio-website-in-less-than-10-minutes-with-github-pages-d0efa8ff56fd
title: Laura W. Dozal # your name (or website title) here
logo: "/images/cool2.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computational Social Scientist with 4+ years of specialization in information behavior and visual analysis through AI and knowledge discovery 
  <br>
  <br><br>
  <a href="https://lwdozal.github.io/CV/">View My CV</a>
  <a href="https://www.linkedin.com/in/laurawerthmann/">View My LinkedIn Profile</a>
  <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
